title: Aki's Epikkk Website
email: hello@akixuu.ca
description: >-
  I know right? Very epic. Super Duper Uper epik.
baseurl: "" # no subpath
url: "https://www.akixuu.ca"

plugins:
  - jekyll-loading-lazy

sass:
    load_paths: 
        - _sass

collections_dir: collections

collections:
  projects:
    output: true
    layout: project

defaults:
  - scope:
      path: "assets/imgs/"
    values:
      image: true
      project_thumbnail: true 

  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"