title: "Aki Xu"
email: "hello@akixuu.ca"
description: >-
  I know right? Very epic. Super Duper Uper epik.
baseurl: ""
url: "https://www.akixuu.ca"

plugins:
  - jekyll-loading-lazy
  - jekyll-sass-converter

theme: null

collections:
  projects:
    output: true
    url: :collection/:name/


defaults:
  - scope:
      path: assets/imgs
    values:
      image: true
      project_thumbnail: true 

  - scope:
      path: ""
      type: projects
    values:
      layout: project

  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"