title: Aki Xu
description: >-
  Hello, what brings you to my website? XD

domain: akixuu.github.io
url: https://akixuu.github.io
baseurl:

sass:
  sass_dir: _sass

collections_dir: collections
collections:
  projects:
    output: true
    permalink: :collection/:name/

defaults:
  - scope:
      path: assets/imgs
    values:
      image: true
      # project_thumbnail: true

  - scope:
      path: ""
      type: projects
    values:
      layout: project

  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

plugins:
  - jekyll-loading-lazy
  - jekyll-sass-converter
  - github-pages

theme: null
