# meta
title: Aki Xu
description: >-
  I know right? Very epic. Super Duper Uper epik.

domain: akixuu.github.io
url: https://akixuu.github.io
baseurl: 

sass:
  sass_dir: _sass
  <option_name2>: <option_value2>

# content
collections:
  projects:
    output: true
    url: :collection/:name/

defaults:
  - scope:
      path: assets/imgs
    values:
      image: true
      project_thumbnail: true 

  - scope:
      path: ""
      type: projects
    values:
      layout: project

  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

# configs
plugins:
  - jekyll-loading-lazy
  - jekyll-sass-converter
  - github-pages

theme: null